FROM node:23-alpine3.20

COPY package*.json ./

RUN npm ci

COPY . .

ENV RSVP_EMAIL_USER=${RSVP_EMAIL_USER}

ENV RSVP_EMAIL_PASS=${RSVP_EMAIL_PASS}

ENV RSVP_EMAIL_HOST=${RSVP_EMAIL_HOST}

ENV RSVP_EMAIL_DEST=${RSVP_EMAIL_DEST}

RUN npm run build

CMD ["node", "build"]