name: Deploy to EC2

permissions:
  id-token: write

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Assume IAM Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-1
          role-to-assume: arn:aws:iam::533267264662:role/WeddingServerRole

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }}
          file: ./Dockerfile
          context: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Start Container via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_ADDR }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 533267264662.dkr.ecr.us-west-1.amazonaws.com
            docker image pull ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }}
            docker image tag ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }} svelte-app:latest
            docker run -p 80:3000 svelte-app:latest