name: Deploy to EC2

permissions:
  id-token: write

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Assume IAM Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-1
          role-to-assume: arn:aws:iam::533267264662:role/WeddingServerRole

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }}
          platforms: linux/arm64
          file: ./Dockerfile
          context: .
          build-args: |
            RSVP_EMAIL_USER=${{ secrets.RSVP_EMAIL_USER }}
            RSVP_EMAIL_PASS=${{ secrets.RSVP_EMAIL_PASS }}
            RSVP_EMAIL_HOST=${{ secrets.RSVP_EMAIL_HOST }}
            RSVP_EMAIL_DEST=${{ secrets.RSVP_EMAIL_DEST }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Start Container via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_ADDR }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}
            docker image pull ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }}
            docker image tag ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }} svelte-app:latest
            docker rm -f svelte-app
            docker run -d --restart unless-stopped --name svelte-app -p 80:3000 svelte-app:latest

      - name: Assume IAM Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-1
          role-to-assume: arn:aws:iam::533267264662:role/WeddingServerRole
